### ISSUE TITLE
How does this related to the Remote for Slides product

### ISSUE THREAD

**Issue by gene1wood** [m4r1vs/slidecontrol#8]
What if any relation is there between this open source project and [Remote for Slides](https://chrome.google.com/webstore/detail/remote-for-slides/pojijacppbhikhkmegdoechbfiiibppi) by [Henry Lim](https://limhenry.xyz/)? I ask because there are all of these parallels between the two projects

* Both are Chrome web extensions combined with progressive web apps
* Both host the PWA at a `.xyz` domain
* Both have a UI with previous and next slides and a button to enable speaker notes
* Both use a 6 digit number to link the PWA to the extension

**Comment by m4r1vs** [comment]
Hi, "slidecontrol" was a high school project of mine and I am in no way affiliated with the other extension you mentioned. My niveri.xyz Domain has expired since I last updated the project so right now it is only accessible at https://mn.uber.space/ and works only when selecting the backend at that domain.

When creating slidecontrol I chose .xyz because it was the cheapest domain. So pure coincidence to answer your question ^^

I don't know how Lim's extension works but connecting two devices together via websocket is very easily achieved with a unique pin.

Thanks for your comment and reminding me to remove the links to the expired domain. If you have any further questions, I'd be glad to answer them :)

Cheers, Marius

**Comment by gene1wood** [comment]
> Or somehow found my little project and reused the idea, it's open source after all

Indeed, this sounds possible. He's got 100k+ installs in the Chrome store so there's that.

Anyhow, thanks for the details. I'll see if I can use your project (as I'm more comfortable granting access to Google Drive to an open source extension).
